/**
 * GEO Optimizer - Database Types
 *
 * TypeScript interfaces matching the Supabase database schema.
 * These types are used throughout the application for type safety.
 *
 * @see docs/database-schema.md for detailed schema documentation
 */

// ============================================================================
// ENUM TYPES
// ============================================================================

/**
 * User subscription plan levels
 */
export type UserPlan = 'free' | 'pro' | 'enterprise';

/**
 * Audit processing status
 */
export type AuditStatus = 'pending' | 'crawling' | 'analyzing' | 'completed' | 'failed';

/**
 * Sub-score status indicators
 */
export type ScoreStatus = 'excellent' | 'optimal' | 'improving' | 'needs_focus';

/**
 * Brand market positioning options
 */
export type BrandPositioning = 'budget' | 'premium' | 'niche' | 'expert';

/**
 * Supported AI engines for simulations
 */
export type AIEngine = 'gpt-4o' | 'claude-3' | 'gemini' | 'perplexity';

/**
 * Recommendation category types
 */
export type RecommendationType =
  | 'semantic_structure'
  | 'citation_health'
  | 'entity_definition'
  | 'answer_first'
  | 'schema_markup'
  | 'content_clarity'
  | 'other';

/**
 * Priority levels for recommendations
 */
export type PriorityLevel = 'critical' | 'high' | 'medium' | 'low';

/**
 * Recommendation completion status
 */
export type RecommendationStatus = 'pending' | 'in_progress' | 'completed' | 'dismissed';

/**
 * Entity density classification
 */
export type EntityDensity = 'low' | 'medium' | 'high';

/**
 * Job processing types
 */
export type JobType = 'crawl' | 'analyze' | 'simulate' | 'optimize' | 'export';

/**
 * Job processing status
 */
export type JobStatus = 'pending' | 'running' | 'completed' | 'failed' | 'cancelled';

/**
 * Alert category types
 */
export type AlertType =
  | 'content_decay'
  | 'interpretation_shift'
  | 'visibility_drop'
  | 'score_change'
  | 'competitor_mention'
  | 'system';

/**
 * Alert severity levels
 */
export type AlertSeverity = 'info' | 'warning' | 'high' | 'critical';

/**
 * Team member role levels
 */
export type TeamRole = 'owner' | 'admin' | 'member' | 'viewer';

// ============================================================================
// JSONB STRUCTURE TYPES
// ============================================================================

/**
 * Crawl configuration settings
 */
export interface CrawlConfig {
  /** Maximum pages to crawl (default: 50) */
  max_pages: number;
  /** URL patterns to include in crawl */
  include_patterns: string[];
  /** URL patterns to exclude from crawl */
  exclude_patterns: string[];
  /** Whether to respect robots.txt (default: true) */
  respect_robots: boolean;
}

/**
 * Individual sub-score with status and description
 */
export interface SubScore {
  /** Score value (0-100) */
  score: number;
  /** Status classification */
  status: ScoreStatus;
  /** Human-readable description */
  description: string;
}

/**
 * Complete sub-scores object for audits
 */
export interface SubScores {
  /** Content clarity and structure score */
  content_clarity?: SubScore;
  /** Entity coverage and density score */
  entity_coverage?: SubScore;
  /** Answer-first content structure score */
  answer_first?: SubScore;
  /** AI readability and parsing score */
  ai_readability?: SubScore;
}

/**
 * AI-generated insight from audit analysis
 */
export interface Insight {
  /** Insight category type */
  type: string;
  /** Short insight title */
  title: string;
  /** Detailed insight description */
  description: string;
  /** Severity/importance level */
  severity: 'info' | 'success' | 'warning' | 'error';
}

/**
 * AI perception tags with confidence scores
 */
export interface PerceptionTags {
  /** Tag name to confidence score (0-100) mapping */
  [tag: string]: number;
}

/**
 * Target audience configuration
 */
export interface Audience {
  /** Description of target demographic */
  demographic_context?: string;
  /** Search intent indicators */
  intent_signals?: string[];
  /** Key decision-making factors */
  decision_factors?: string[];
}

/**
 * AI content guardrail rule
 */
export interface Guardrail {
  /** What to avoid in content */
  avoid: string;
  /** Reason for avoiding */
  reason: string;
}

/**
 * Machine-readable brand profile generated by AI
 */
export interface MachineProfile {
  /** Primary brand intent identifier */
  intent?: string;
  /** Target audience segment identifiers */
  audience_cluster?: string[];
  /** Narrative priority weights (0-1) */
  narrative_weight?: Record<string, number>;
  /** Words/phrases to avoid */
  forbidden_tokens?: string[];
  /** Overall alignment score */
  alignmentScore?: number;
}

/**
 * AI reasoning step in simulation
 */
export interface ReasoningStep {
  /** Step identifier */
  step: string;
  /** Description of what happened */
  description: string;
}

/**
 * Detected entity in content
 */
export interface Entity {
  /** Entity name */
  name: string;
  /** Entity type classification */
  type: 'topic' | 'tech' | 'brand' | 'person' | 'concept';
  /** Detection status */
  status: 'detected' | 'missing' | 'weak';
}

/**
 * Execution step for recommendations
 */
export interface ExecutionStep {
  /** Step order number */
  order: number;
  /** Action to take */
  action: string;
  /** Additional details */
  details?: string;
}

/**
 * Alert data for content decay alerts
 */
export interface ContentDecayAlertData {
  page_url: string;
  previous_authority: 'primary' | 'secondary' | 'tertiary';
  current_authority: 'primary' | 'secondary' | 'tertiary';
  affected_query: string;
}

/**
 * Alert data for score change alerts
 */
export interface ScoreChangeAlertData {
  previous_score: number;
  current_score: number;
  change_percentage: number;
  affected_metrics: string[];
}

/**
 * Alert data for visibility drop alerts
 */
export interface VisibilityDropAlertData {
  query: string;
  previous_position: number;
  current_position: number;
  competitor_gained?: string;
}

/**
 * Union type for all alert data types
 */
export type AlertData =
  | ContentDecayAlertData
  | ScoreChangeAlertData
  | VisibilityDropAlertData
  | Record<string, unknown>;

// ============================================================================
// TABLE ROW TYPES
// ============================================================================

/**
 * User profile row type
 */
export interface Profile {
  /** User ID (from auth.users) */
  id: string;
  /** User email address */
  email: string;
  /** User display name */
  full_name: string | null;
  /** Profile picture URL */
  avatar_url: string | null;
  /** Subscription plan */
  plan: UserPlan;
  /** Record creation timestamp */
  created_at: string;
  /** Last update timestamp */
  updated_at: string;
}

/**
 * Site row type
 */
export interface Site {
  /** Site UUID */
  id: string;
  /** Owner user ID */
  user_id: string;
  /** Website domain */
  domain: string;
  /** Friendly site name */
  name: string | null;
  /** Crawl configuration */
  crawl_config: CrawlConfig;
  /** Last successful crawl timestamp */
  last_crawl_at: string | null;
  /** Record creation timestamp */
  created_at: string;
  /** Last update timestamp */
  updated_at: string;
}

/**
 * Job row type
 */
export interface Job {
  /** Job UUID */
  id: string;
  /** Owner user ID */
  user_id: string;
  /** Job type */
  type: JobType;
  /** Current status */
  status: JobStatus;
  /** Progress percentage (0-100) */
  progress: number;
  /** Human-readable progress message */
  progress_message: string | null;
  /** Input parameters */
  payload: Record<string, unknown>;
  /** Output data */
  result: Record<string, unknown> | null;
  /** Error message if failed */
  error: string | null;
  /** Detailed error information */
  error_details: Record<string, unknown> | null;
  /** Number of retry attempts */
  retry_count: number;
  /** Maximum retry attempts */
  max_retries: number;
  /** External service reference ID */
  external_id: string | null;
  /** External service name */
  external_service: string | null;
  /** Record creation timestamp */
  created_at: string;
  /** Job start timestamp */
  started_at: string | null;
  /** Job completion timestamp */
  completed_at: string | null;
}

/**
 * Audit row type
 */
export interface Audit {
  /** Audit UUID */
  id: string;
  /** Associated site ID */
  site_id: string;
  /** Associated job ID */
  job_id: string | null;
  /** Current status */
  status: AuditStatus;
  /** Overall GEO visibility score (0-100) */
  overall_score: number | null;
  /** Score change vs previous audit */
  score_change: number | null;
  /** Detailed sub-scores */
  sub_scores: SubScores;
  /** AI-generated insights */
  insights: Insight[];
  /** AI perception tags */
  perception_tags: PerceptionTags;
  /** Common AI keywords */
  ai_keywords: string[];
  /** Reference to stored crawl data */
  crawl_data_url: string | null;
  /** Record creation timestamp */
  created_at: string;
  /** Audit completion timestamp */
  completed_at: string | null;
}

/**
 * Brand voice row type
 */
export interface BrandVoice {
  /** Brand voice UUID */
  id: string;
  /** Associated site ID */
  site_id: string;
  /** Market positioning */
  positioning: BrandPositioning | null;
  /** Detailed positioning description */
  positioning_description: string | null;
  /** Target audience configuration */
  audience: Audience;
  /** Unique selling points */
  differentiators: string[];
  /** AI content guardrails */
  guardrails: Guardrail[];
  /** AI-generated machine-readable profile */
  machine_profile: MachineProfile;
  /** Brand alignment score (0-100) */
  alignment_score: number | null;
  /** Record creation timestamp */
  created_at: string;
  /** Last update timestamp */
  updated_at: string;
}

/**
 * Simulation row type
 */
export interface Simulation {
  /** Simulation UUID */
  id: string;
  /** Associated site ID */
  site_id: string;
  /** Associated job ID */
  job_id: string | null;
  /** User query being simulated */
  query: string;
  /** AI engine used */
  engine: AIEngine;
  /** Generated AI response */
  ai_response: string | null;
  /** Whether brand was mentioned */
  brand_mentioned: boolean | null;
  /** Tone alignment score (0-100) */
  tone_match: number | null;
  /** AI reasoning steps */
  reasoning_path: ReasoningStep[];
  /** GEO optimization tip */
  geo_tip: string | null;
  /** Record creation timestamp */
  created_at: string;
}

/**
 * Recommendation row type
 */
export interface Recommendation {
  /** Recommendation UUID */
  id: string;
  /** Associated audit ID */
  audit_id: string;
  /** Recommendation category */
  type: RecommendationType;
  /** Priority level */
  priority: PriorityLevel;
  /** Recommendation title */
  title: string;
  /** Detailed description */
  description: string | null;
  /** Why this matters for AI */
  why_matters: string | null;
  /** Recommended action */
  action: string | null;
  /** Expected impact */
  estimated_impact: string | null;
  /** Time estimate */
  estimated_time: string | null;
  /** Step-by-step execution guide */
  execution_steps: ExecutionStep[];
  /** Code example if applicable */
  code_snippet: string | null;
  /** Current status */
  status: RecommendationStatus;
  /** Completion timestamp */
  completed_at: string | null;
  /** Record creation timestamp */
  created_at: string;
}

/**
 * Content row type
 */
export interface Content {
  /** Content UUID */
  id: string;
  /** Associated site ID */
  site_id: string;
  /** Page URL */
  url: string;
  /** Page title */
  title: string | null;
  /** Original content text */
  original_content: string | null;
  /** AI-optimized content */
  optimized_content: string | null;
  /** Content GEO score (0-100) */
  geo_score: number | null;
  /** Entity density classification */
  entity_density: EntityDensity | null;
  /** Citation potential (0.0-10.0) */
  citation_potential: number | null;
  /** Detected entities */
  entities: Entity[];
  /** Optimization suggestions */
  optimization_tips: string[];
  /** Last optimization timestamp */
  last_optimized_at: string | null;
  /** Record creation timestamp */
  created_at: string;
  /** Last update timestamp */
  updated_at: string;
}

/**
 * Alert row type
 */
export interface Alert {
  /** Alert UUID */
  id: string;
  /** Associated site ID */
  site_id: string;
  /** Alert type */
  type: AlertType;
  /** Severity level */
  severity: AlertSeverity;
  /** Alert title */
  title: string;
  /** Alert message */
  message: string;
  /** Additional alert data */
  data: AlertData;
  /** Action URL */
  action_url: string | null;
  /** Action button label */
  action_label: string | null;
  /** Read status */
  read: boolean;
  /** Dismissed status */
  dismissed: boolean;
  /** Record creation timestamp */
  created_at: string;
}

/**
 * Team member row type
 */
export interface TeamMember {
  /** Team member UUID */
  id: string;
  /** Associated site ID */
  site_id: string;
  /** Team member user ID */
  user_id: string;
  /** Member role */
  role: TeamRole;
  /** User who sent invitation */
  invited_by: string | null;
  /** Invitation timestamp */
  invited_at: string;
  /** Acceptance timestamp (null if pending) */
  accepted_at: string | null;
}

// ============================================================================
// INSERT TYPES (for creating new records)
// ============================================================================

/**
 * Profile insert type (id comes from auth.users)
 */
export interface ProfileInsert {
  id: string;
  email: string;
  full_name?: string | null;
  avatar_url?: string | null;
  plan?: UserPlan;
}

/**
 * Site insert type
 */
export interface SiteInsert {
  user_id: string;
  domain: string;
  name?: string | null;
  crawl_config?: CrawlConfig;
}

/**
 * Job insert type
 */
export interface JobInsert {
  user_id: string;
  type: JobType;
  payload?: Record<string, unknown>;
  status?: JobStatus;
}

/**
 * Audit insert type
 */
export interface AuditInsert {
  site_id: string;
  job_id?: string | null;
  status?: AuditStatus;
}

/**
 * Brand voice insert type
 */
export interface BrandVoiceInsert {
  site_id: string;
  positioning?: BrandPositioning | null;
  positioning_description?: string | null;
  audience?: Audience;
  differentiators?: string[];
  guardrails?: Guardrail[];
  machine_profile?: MachineProfile;
  alignment_score?: number | null;
}

/**
 * Simulation insert type
 */
export interface SimulationInsert {
  site_id: string;
  query: string;
  engine?: AIEngine;
  job_id?: string | null;
  ai_response?: string | null;
  brand_mentioned?: boolean | null;
  tone_match?: number | null;
  reasoning_path?: ReasoningStep[];
  geo_tip?: string | null;
}

/**
 * Recommendation insert type
 */
export interface RecommendationInsert {
  audit_id: string;
  type: RecommendationType;
  priority: PriorityLevel;
  title: string;
  description?: string | null;
  why_matters?: string | null;
  action?: string | null;
  estimated_impact?: string | null;
  estimated_time?: string | null;
  execution_steps?: ExecutionStep[];
  code_snippet?: string | null;
  status?: RecommendationStatus;
}

/**
 * Content insert type
 */
export interface ContentInsert {
  site_id: string;
  url: string;
  title?: string | null;
  original_content?: string | null;
  optimized_content?: string | null;
  geo_score?: number | null;
  entity_density?: EntityDensity | null;
  citation_potential?: number | null;
  entities?: Entity[];
  optimization_tips?: string[];
}

/**
 * Alert insert type
 */
export interface AlertInsert {
  site_id: string;
  type: AlertType;
  severity: AlertSeverity;
  title: string;
  message: string;
  data?: AlertData;
  action_url?: string | null;
  action_label?: string | null;
}

/**
 * Team member insert type
 */
export interface TeamMemberInsert {
  site_id: string;
  user_id: string;
  role: TeamRole;
  invited_by?: string | null;
}

// ============================================================================
// UPDATE TYPES (for updating existing records)
// ============================================================================

/**
 * Profile update type
 */
export interface ProfileUpdate {
  email?: string;
  full_name?: string | null;
  avatar_url?: string | null;
  plan?: UserPlan;
}

/**
 * Site update type
 */
export interface SiteUpdate {
  domain?: string;
  name?: string | null;
  crawl_config?: CrawlConfig;
  last_crawl_at?: string | null;
}

/**
 * Job update type
 */
export interface JobUpdate {
  status?: JobStatus;
  progress?: number;
  progress_message?: string | null;
  result?: Record<string, unknown> | null;
  error?: string | null;
  error_details?: Record<string, unknown> | null;
  retry_count?: number;
  external_id?: string | null;
  external_service?: string | null;
  started_at?: string | null;
  completed_at?: string | null;
}

/**
 * Audit update type
 */
export interface AuditUpdate {
  job_id?: string | null;
  status?: AuditStatus;
  overall_score?: number | null;
  score_change?: number | null;
  sub_scores?: SubScores;
  insights?: Insight[];
  perception_tags?: PerceptionTags;
  ai_keywords?: string[];
  crawl_data_url?: string | null;
  completed_at?: string | null;
}

/**
 * Brand voice update type
 */
export interface BrandVoiceUpdate {
  positioning?: BrandPositioning | null;
  positioning_description?: string | null;
  audience?: Audience;
  differentiators?: string[];
  guardrails?: Guardrail[];
  machine_profile?: MachineProfile;
  alignment_score?: number | null;
}

/**
 * Simulation update type (limited fields)
 */
export interface SimulationUpdate {
  ai_response?: string | null;
  brand_mentioned?: boolean | null;
  tone_match?: number | null;
  reasoning_path?: ReasoningStep[];
  geo_tip?: string | null;
}

/**
 * Recommendation update type
 */
export interface RecommendationUpdate {
  status?: RecommendationStatus;
  completed_at?: string | null;
}

/**
 * Content update type
 */
export interface ContentUpdate {
  title?: string | null;
  original_content?: string | null;
  optimized_content?: string | null;
  geo_score?: number | null;
  entity_density?: EntityDensity | null;
  citation_potential?: number | null;
  entities?: Entity[];
  optimization_tips?: string[];
  last_optimized_at?: string | null;
}

/**
 * Alert update type
 */
export interface AlertUpdate {
  read?: boolean;
  dismissed?: boolean;
}

/**
 * Team member update type
 */
export interface TeamMemberUpdate {
  role?: TeamRole;
  accepted_at?: string | null;
}

// ============================================================================
// DATABASE TYPE (Supabase generated types structure)
// ============================================================================

/**
 * Complete database type definition for Supabase client
 */
export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: Profile;
        Insert: ProfileInsert;
        Update: ProfileUpdate;
      };
      sites: {
        Row: Site;
        Insert: SiteInsert;
        Update: SiteUpdate;
      };
      jobs: {
        Row: Job;
        Insert: JobInsert;
        Update: JobUpdate;
      };
      audits: {
        Row: Audit;
        Insert: AuditInsert;
        Update: AuditUpdate;
      };
      brand_voices: {
        Row: BrandVoice;
        Insert: BrandVoiceInsert;
        Update: BrandVoiceUpdate;
      };
      simulations: {
        Row: Simulation;
        Insert: SimulationInsert;
        Update: SimulationUpdate;
      };
      recommendations: {
        Row: Recommendation;
        Insert: RecommendationInsert;
        Update: RecommendationUpdate;
      };
      contents: {
        Row: Content;
        Insert: ContentInsert;
        Update: ContentUpdate;
      };
      alerts: {
        Row: Alert;
        Insert: AlertInsert;
        Update: AlertUpdate;
      };
      team_members: {
        Row: TeamMember;
        Insert: TeamMemberInsert;
        Update: TeamMemberUpdate;
      };
    };
    Enums: {
      user_plan: UserPlan;
      audit_status: AuditStatus;
      score_status: ScoreStatus;
      brand_positioning: BrandPositioning;
      ai_engine: AIEngine;
      recommendation_type: RecommendationType;
      priority_level: PriorityLevel;
      recommendation_status: RecommendationStatus;
      entity_density: EntityDensity;
      job_type: JobType;
      job_status: JobStatus;
      alert_type: AlertType;
      alert_severity: AlertSeverity;
      team_role: TeamRole;
    };
  };
}

// ============================================================================
// UTILITY TYPES
// ============================================================================

/**
 * Extract table names from database
 */
export type TableName = keyof Database['public']['Tables'];

/**
 * Extract row type for a given table
 */
export type TableRow<T extends TableName> = Database['public']['Tables'][T]['Row'];

/**
 * Extract insert type for a given table
 */
export type TableInsert<T extends TableName> = Database['public']['Tables'][T]['Insert'];

/**
 * Extract update type for a given table
 */
export type TableUpdate<T extends TableName> = Database['public']['Tables'][T]['Update'];

// ============================================================================
// RELATION TYPES (for joined queries)
// ============================================================================

/**
 * Site with related brand voice
 */
export interface SiteWithBrandVoice extends Site {
  brand_voices: BrandVoice | null;
}

/**
 * Site with all related data
 */
export interface SiteWithRelations extends Site {
  brand_voices: BrandVoice | null;
  audits: Audit[];
  simulations: Simulation[];
  contents: Content[];
  alerts: Alert[];
  team_members: TeamMember[];
}

/**
 * Audit with related recommendations
 */
export interface AuditWithRecommendations extends Audit {
  recommendations: Recommendation[];
}

/**
 * Audit with site information
 */
export interface AuditWithSite extends Audit {
  sites: Site;
}

/**
 * Full audit with all relations
 */
export interface AuditWithRelations extends Audit {
  sites: Site;
  recommendations: Recommendation[];
  jobs: Job | null;
}

/**
 * Team member with user profile
 */
export interface TeamMemberWithProfile extends TeamMember {
  profiles: Profile;
}

/**
 * Alert with site information
 */
export interface AlertWithSite extends Alert {
  sites: Site;
}
